server:
  port: ${PORT}

spring:
  application:
    name: server

  # database
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
#    url: jdbc:postgresql://localhost:5433/quantumcare
#    username: postgres
#    password: p3ac3123.
    driver-class-name: org.postgresql.Driver

  # hibernate configuration (JPA)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false # enable in dev mode
    properties:
      hibernate:
        format_sql: true
    open-in-view: false # enable in dev mode

  # env properties
  config:
    import: classpath:.env.properties # ensure the .env stays in the resources folder

# jwt configuration
jwt:
  secret: ${JWT_SECRET}
  validity: ${JWT_VALIDITY}

# frontend configuration
frontend:
  url: ${FRONTEND_URL}